// <auto-generated />
using System;
using Acceloka.Api.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Acceloka.Api.Migrations
{
    [DbContext(typeof(AccelokaDbContext))]
    [Migration("20260302054036_AddTicketImageUrl")]
    partial class AddTicketImageUrl
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Acceloka.Api.Infrastructure.Persistence.Entities.BookedTicket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("BookedTickets");
                });

            modelBuilder.Entity("Acceloka.Api.Infrastructure.Persistence.Entities.BookedTicketDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BookedTicketId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BookedTicketId");

                    b.HasIndex("TicketId");

                    b.ToTable("BookedTicketDetails", t =>
                        {
                            t.HasCheckConstraint("CK_BookedTicketDetails_Quantity_Positive", "\"Quantity\" > 0");
                        });
                });

            modelBuilder.Entity("Acceloka.Api.Infrastructure.Persistence.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Acceloka.Api.Infrastructure.Persistence.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Acceloka.Api.Infrastructure.Persistence.Entities.Ticket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<int>("Quota")
                        .HasColumnType("integer");

                    b.Property<string>("TicketCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TicketName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("TicketCode")
                        .IsUnique();

                    b.ToTable("Tickets", t =>
                        {
                            t.HasCheckConstraint("CK_Tickets_Quota_Positive", "\"Quota\" > 0");
                        });
                });

            modelBuilder.Entity("Acceloka.Api.Infrastructure.Persistence.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Acceloka.Api.Infrastructure.Persistence.Entities.BookedTicket", b =>
                {
                    b.HasOne("Acceloka.Api.Infrastructure.Persistence.Entities.User", "User")
                        .WithMany("BookedTickets")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("Acceloka.Api.Infrastructure.Persistence.Entities.BookedTicketDetail", b =>
                {
                    b.HasOne("Acceloka.Api.Infrastructure.Persistence.Entities.BookedTicket", "BookedTicket")
                        .WithMany("Details")
                        .HasForeignKey("BookedTicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Acceloka.Api.Infrastructure.Persistence.Entities.Ticket", "Ticket")
                        .WithMany("BookedTicketDetails")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BookedTicket");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("Acceloka.Api.Infrastructure.Persistence.Entities.RefreshToken", b =>
                {
                    b.HasOne("Acceloka.Api.Infrastructure.Persistence.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Acceloka.Api.Infrastructure.Persistence.Entities.Ticket", b =>
                {
                    b.HasOne("Acceloka.Api.Infrastructure.Persistence.Entities.Category", "Category")
                        .WithMany("Tickets")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Acceloka.Api.Infrastructure.Persistence.Entities.BookedTicket", b =>
                {
                    b.Navigation("Details");
                });

            modelBuilder.Entity("Acceloka.Api.Infrastructure.Persistence.Entities.Category", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("Acceloka.Api.Infrastructure.Persistence.Entities.Ticket", b =>
                {
                    b.Navigation("BookedTicketDetails");
                });

            modelBuilder.Entity("Acceloka.Api.Infrastructure.Persistence.Entities.User", b =>
                {
                    b.Navigation("BookedTickets");

                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
